apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: web
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
