apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: {{ .Values.hostname }}
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
