namespace: flask-app

replicaCount: 1

hostname: Host(`flask.aws.elysium-space.com`)  # Replace with your domain

image:
  repository: ivandevelop/flask-app # Replace with your Docker image repository
  pullPolicy: Always
  tag: latest # Replace with your Docker image tag

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
